[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port = 8888
  publish = "."
  functions = "netlify/functions"
  autoLaunch = false

# Run send-reminders every hour to check for appointments within the next 24h
[functions."send-reminders"]
  schedule = "0 * * * *"
